name: MLB Home Run Alert

on:
  schedule:
    - cron: '*/25 * * * *'  # Runs every 25 minutes

jobs:
  send_home_run_alert:
    runs-on: ubuntu-latest

    steps:
    - name: Fetch and send home run alert
      run: |
        today=$(date -u +"%Y-%m-%d")

        all_hrs=$(curl -s "https://site.api.espn.com/apis/site/v2/sports/baseball/mlb/scoreboard" \
        | jq -r '
          .events[]?.competitions[]?.leaders[]? 
          | select(.name == "homeRuns") 
          | .leaders[]? 
          | select(.value > 0) 
          | "\(.athlete.displayName) - \(.team.displayName) - HRs: \(.value | tonumber)"'
        )

        echo "Fetched Home Runs: $all_hrs"

        if [ -n "$all_hrs" ]; then
          message="🚨 Today's MLB Home Run Hitters 🚀\n\n$all_hrs_
