name: MLB Home Run Alerts

on:
  schedule:
    # Run every 25 minutes from 4:00 PM to 9:25 PM Pacific Time (11:00 PM to 4:25 AM UTC)
    - cron: '0,25,50 23 * * *'
    - cron: '15,40 0-4 * * *'

jobs:
  send-home-run-alerts:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq and curl
        run: sudo apt-get update && sudo apt-get install -y jq curl

      - name: Send Home Run Alert
        run: |
          # Convert to America/New_York to match ESPN's scoreboard timezone
          today=$(TZ=America/New_York date +%Y%m%d)
          echo "Checking for home runs on: $today (ET)"

          all_hrs=$(curl -s "https://site.api.espn.com/apis/site/v2/sports/baseball/mlb/scoreboard?dates=$today" \
            | jq -r '
              .events[]?.competitions[]?.leaders[]? 
              | select(.name == "homeRuns") 
              | .leaders[]? 
              | select(.value > 0) 
              | "\(.athlete.displayName) of \(.team.shortDisplayName) - HRs: \(.value | tonumber)"'
          )

          if [ -n "$all_hrs" ]; then
            message="🚨 MLB Home Runs for $(TZ=America/New_York date +%Y-%m-%d) 🚀%0A%0A$all_hrs"
            echo "Sending alert:"
            echo "$message"
            curl -s -X POST "https://api.telegram.org/bot7941683123:AAEXCQ8C-V_3cHU_
