name: Home Run Notification

on:
  schedule:
    - cron: '*/5 * * * *'  # This runs every 5 minutes

jobs:
  run_homerun_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JQ
        run: sudo apt-get install jq

      - name: Fetch home run data and send alert
        run: |
          # Fetch the latest scoreboard data from ESPN API
          latest_hr=$(curl -s https://site.api.espn.com/apis/site/v2/sports/baseball/mlb/scoreboard | jq -r '
            .events[].competitions[].competitors[].statistics[]? 
            | select(.name=="homeRuns") 
            | .leaders[0].athlete.displayName + " - " + .leaders[0].team.shortDisplayName' 
            | head -n 1)

          # If a home run is found, compare with the last seen home run
          if [ -n "$latest_hr" ]; then
            # Check if the last home run is stored in a file or GitHub cache
            if [ -f last_home_run.txt ]; then
              last_home_run=$(cat last_home_run.txt)
            else
              last_home_run=""
            fi

            # If the home run is new, send the message and update the last home run
            if [ "$latest_hr" != "$last_home_run" ]; then
              # Update the stored home run
              echo $latest_hr > last_home_run.txt

              # Send a Telegram message
              curl -s -X POST "https://api.telegram.org/bot<YOUR_BOT_TOKEN>/sendMessage" \
                -d chat_id=<YOUR_CHAT_ID> \
                -d text="🚨 Home Run Alert: $latest_hr 🚀"
            else
              echo "No new home runs."
            fi
          else
            echo "No new home runs."
          fi
