# Fetch the latest scoreboard data from ESPN API
latest_hr=$(curl -s https://site.api.espn.com/apis/site/v2/sports/baseball/mlb/scoreboard | jq -r '.events[].competitions[].competitors[].statistics[]? | select(.name=="homeRuns") | .leaders[0]?.athlete.displayName + " - " + .leaders[0]?.team.shortDisplayName' | head -n 1)

# If a home run is found, compare with the last seen home run
if [ -n "$latest_hr" ]; then
  # Check if the last home run is stored in a file or GitHub cache
  if [ -f last_home_run.txt ]; then
    last_home_run=$(cat last_home_run.txt)
  else
    last_home_run=""
  fi

  # If the home run is new, send the message and update the last home run
  if [ "$latest_hr" != "$last_home_run" ]; then
    # Update the stored home run
    echo "$latest_hr" > last_home_run.txt

    # Send a Telegram message
    curl -s -X POST "https://api.telegram.org/bot7941683123:AAEXCQ8C-V_3cHUJVI6zJx9E0CNunP9kPs8/sendMessage" \
      -d chat_id=7613640636 \
      -d text="🚨 Home Run Alert: $latest_hr 🚀"
  else
    echo "No new home runs."
  fi
else
  echo "No new home runs."
fi
