name: MLB Home Run Alert

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes
  workflow_dispatch:       # Allows manual triggering from GitHub UI

jobs:
  check_home_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Check for new home run
        run: |
          # Fetch the latest scoreboard data from ESPN API
          latest_hr=$(curl -s https://site.api.espn.com/apis/site/v2/sports/baseball/mlb/scoreboard | jq -r '
            .events[].competitions[].competitors[].statistics[]? 
            | select(.name=="homeRuns") 
            | .leaders[0]?.athlete.displayName + " - " + .leaders[0]?.team.shortDisplayName' | head -n 1)
